
---

---
# Manipulação de dataframe - TAREFA 2 - Parte III
---

---

##1-) Leitura dos dados

A base de dados [Churn_Modelling](https://github.com/malegopc/DSBD/blob/main/Datasets/Churn/Churn_Modelling.csv) é utilizada para prever (classificar) quando um cliente irá parar de utilizar o serviço de um banco.

Conjunto de dados (características):

* Número de Instâncias: 10.000

* Número de Atributos: 13 atributos (incluindo o target)

* Informações dos Atributos:

  1. RowNumber
  2. CustomerId
  3. Surname
  4. CreditScore
  5. Geography
  6. Gender Age
  7. Tenure
  8. Balance
  9. NumOfProducts
  10. HasCrCard
  11. IsActiveMember
  12. EstimatedSalary
  13. Exited (variável de destino - target)

*Clone o repositório de dados da disciplina (https://github.com/malegopc/DSBD), faça a leitura do arquivo **Churn_Modelling.csv** disponível na pasta [Churn_Modelling](https://github.com/malegopc/DSBD/blob/main/Datasets/Churn) e armazene-o numa variável do tipo dataframe. Basta utilizar a função [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) da biblioteca pandas.*

In [58]:
#importações
import pandas as pd
import os
from google.colab import files

In [59]:
#clonando repositorio
!git clone https://github.com/malegopc/DSBD.git

fatal: destination path 'DSBD' already exists and is not an empty directory.

In [60]:
#caminho do arquivo
path_arquivo = 'DSBD/Datasets/Churn/Churn_Modelling.csv'

##2-) Visualização do dataframe

*Mostre as 5 primeiras e as 5 últimas linhas do dataframe.*

In [61]:
#lendo o dataframe

dataframe = pd.read_csv(path_arquivo)

In [62]:
#mostrando as 5 primeiras linhas
dataframe.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [63]:
#mostrando as 5 ultimas linhas
dataframe.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

##3-) Eliminação manual de variáveis

*Elimine as variáveis (colunas): 'RowNumber', 'CustomerId' e 'Surname'.*

In [64]:
#usando o metodo .drop
dataframe.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

##4-) Dados ausentes

*Verifique se há dados ausentes no dataframe.*

In [65]:
#utilizando o metodo .info
dataframe.info()

#utilizando o metodo .isnull e .sum() pra somar
dataframe.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

## 5-) Separa as variáveis

*Utilizando a função **[iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html?highlight=iloc#pandas.DataFrame.iloc)**, copie para uma variável "X" os valores de todas as variáveis (colunas) do dataframe, exceto os valores da variável "Exited".*

*E copie para uma variável "y" somente os valores da variável "Exited".*

In [66]:
#copiando p x todas as linhas até a penúltima
X = dataframe.iloc[:, :-1]

#copiando p y
Y = dataframe.iloc[:, -1]

#mostrando dados das variáveis copiadas
print("Formato de X (linhas, colunas): ", X.shape)
print("Formato de Y (linhas, colunas): ", Y.shape)

Formato de X (linhas, colunas):  (10000, 10)
Formato de Y (linhas, colunas):  (10000,)